export default function Settings() {
  return (
    <div className="container">
      <h1>Settings → Integrations</h1>
      <div className="card">
        <p>Set these environment variables in Vercel (Project → Settings → Environment Variables):</p>
        <pre><code>
SUPABASE_URL=...
SUPABASE_ANON_KEY=...
SUPABASE_SERVICE_ROLE=...   (server only)
YOUTUBE_API_KEY=...
REDDIT_CLIENT_ID=...
REDDIT_CLIENT_SECRET=...
REDDIT_USERNAME=...
REDDIT_PASSWORD=...
REDDIT_USER_AGENT=TrendRadar/1.0 (by u/YourUsername)
        </code></pre>
      </div>
    </div>
  );
}
